-- CRIAR BD
CREATE DATABASE GREENHOUSE;

-- DEFINIR BD COMO PADRÃO / UTILIZÁVEL
USE GREENHOUSE;

-- CRIAR TABELA/ENTIDADE
CREATE TABLE `PLANTS` (
 	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL 
		DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE current_timestamp,
	primary key `PK_PLANTS` (`PLANT_NAME`)
);
-- ALTER table PLANTS CHANGE SENSOR_NAME SENSOR_VALUE FLOAT;

-- VISUALIZAR TODAS AS OCORRENCIAS EM PLANTS
SELECT * FROM `PLANTS`;

SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM `PLANTS`;

INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES('ROSA', 0.2319);

-- INSERIR MÚLTIPLOS REGISTROS DE UMA VEZ
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES('CACTUS', 0.2411),
	  ('GIRRASOL', 0.3112),
      ('ORQUIDEA', 0.4102),
      ('LÍRIO', 0.5566);
      
-- consulta aplicando filtros
SELECT * 
FROM PLANTS 
WHERE PLANT_NAME = 'CACTUS';

-- FILTROS COMPOSTOS COM OPERADORES AND OR XOR ETC
SELECT *
FROM PLANTS
WHERE PLANTS_NAME <> 'CANABIS'
AND SENSOR_VALUE < 0.5566
AND SENSOR_VALUE > 0.2411;
 