CREATE DATABASE SIMPOSIO_TECNOLOGIA2;  
USE SIMPOSIO_TECNOLOGIA2;

CREATE TABLE PESSOAS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    DATA_NASC DATE NOT NULL
);

CREATE TABLE SIMPOSIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_REALIZACAO DATE NOT NULL
);

CREATE TABLE MINI_CURSOS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_MINICURSO DATE NOT NULL,
    ID_SIMPOSIO INT NOT NULL,
    CONSTRAINT FK_CURSO_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID)
);

CREATE TABLE PALESTRAS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_PALESTRA DATE NOT NULL,
    ID_SIMPOSIO INT NOT NULL,
    CONSTRAINT FK_PALESTRA_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID)
);

CREATE TABLE SIMPOSIO_PESSOA(
    ID_SIMPOSIO INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY (ID_SIMPOSIO, ID_PESSOA),
    CONSTRAINT FK_ID_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE INSCRICAO_MINICURSOS(
    ID_PESSOA INT NOT NULL,
    ID_MINICURSO INT NOT NULL,
    PRIMARY KEY (ID_PESSOA, ID_MINICURSO),
    E_MINISTRADOR BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_INSCRICAO DATE NOT NULL,
    STATUS_INSCRICAO VARCHAR(255) NOT NULL,  
    CONSTRAINT FK_INSCRICAO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID),
    CONSTRAINT FK_INSCRICAO_MINICURSO FOREIGN KEY(ID_MINICURSO) REFERENCES MINI_CURSOS(ID)
);

CREATE TABLE INSCRICAO_PALESTRA(
    ID_PESSOA INT NOT NULL,
    ID_PALESTRA INT NOT NULL,
    PRIMARY KEY (ID_PESSOA, ID_PALESTRA),
    E_MINISTRADOR BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_INSCRICAO DATE NOT NULL,
    STATUS_INSCRICAO VARCHAR(255) NOT NULL,  
    CONSTRAINT FK_INSCRICAO_PESSOA_PALESTRA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID),
    CONSTRAINT FK_INSCRICAO_PALESTRA FOREIGN KEY(ID_PALESTRA) REFERENCES PALESTRAS(ID)
);

CREATE TABLE COMISSAO_AVALIADORA(
    ID INT NOT NULL PRIMARY KEY,
    ID_PESSOA INT NOT NULL, 
    CARGO VARCHAR(255) NOT NULL,   
    AREA_ESPECIALIZACAO VARCHAR(255) NOT NULL,  
    CONSTRAINT FK_COMISSAO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE ARTIGOS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,  
    RESUMO TEXT,
    DATA_CRIACAO DATE NOT NULL,
    ID_SIMPOSIO INT NOT NULL,
    ID_AUTOR INT NOT NULL,
    CONSTRAINT FK_ARTIGO_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID),
    CONSTRAINT FK_ARTIGO_PESSOA FOREIGN KEY(ID_AUTOR) REFERENCES PESSOAS(ID)
);

CREATE TABLE ARTIGOS_PESSOA(
    ID_ARTIGO INT NOT NULL, 
    ID_PESSOA INT NOT NULL,  
    PRIMARY KEY (ID_ARTIGO, ID_PESSOA),
    CONSTRAINT FK_ARTIGO_PUBLICADOR FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGOS(ID),
    CONSTRAINT FK_PESSOA_ARTIGO FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE AVALIACAO_ARTIGO(
    ID_ARTIGO INT NOT NULL, 
    ID_COMISSAO_AVALIADORA INT NOT NULL, 
    PRIMARY KEY (ID_ARTIGO, ID_COMISSAO_AVALIADORA),
    NOTA INT NOT NULL,  
    COMENTARIOS TEXT, 
    CONSTRAINT FK_ARTIGO FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGOS(ID),
    CONSTRAINT FK_COMISSAO_AVALIADORA FOREIGN KEY(ID_COMISSAO_AVALIADORA) REFERENCES COMISSAO_AVALIADORA(ID)
);

INSERT INTO PESSOAS (NOME, CPF, DATA_NASC) VALUES
('João Silva', '123.456.789-00', '1980-05-15'),
('Maria Oliveira', '987.654.321-00', '1975-08-22'),
('Carlos Pereira', '111.222.333-44', '1990-12-10');

INSERT INTO SIMPOSIO (NOME, DATA_REALIZACAO) VALUES
('Simpósio de Tecnologia 2023', '2023-09-15'),
('Conferência de Inovação 2024', '2024-03-10');

INSERT INTO MINI_CURSOS (NOME, DATA_MINICURSO, ID_SIMPOSIO) VALUES
('Introdução à IA', '2023-09-16', 1),
('Big Data e Análise', '2023-09-17', 1);

INSERT INTO PALESTRAS (NOME, DATA_PALESTRA, ID_SIMPOSIO) VALUES
('Futuro da Tecnologia', '2023-09-15', 1),
('Inovação em Software', '2023-09-15', 1);

INSERT INTO SIMPOSIO_PESSOA (ID_SIMPOSIO, ID_PESSOA) VALUES
(1, 1),
(1, 2),
(2, 3);

INSERT INTO INSCRICAO_MINICURSOS (ID_PESSOA, ID_MINICURSO, E_MINISTRADOR, DATA_INSCRICAO, STATUS_INSCRICAO) VALUES
(1, 1, FALSE, '2023-08-01', 'Confirmada'),
(2, 2, FALSE, '2023-08-02', 'Confirmada');

INSERT INTO INSCRICAO_PALESTRA (ID_PESSOA, ID_PALESTRA, E_MINISTRADOR, DATA_INSCRICAO, STATUS_INSCRICAO) VALUES
(3, 1, FALSE, '2023-08-03', 'Confirmada');

INSERT INTO COMISSAO_AVALIADORA (ID, ID_PESSOA, CARGO, AREA_ESPECIALIZACAO) VALUES
(1, 2, 'Membro', 'Inteligência Artificial'),
(2, 3, 'Presidente', 'Big Data');

INSERT INTO ARTIGOS (TITULO, RESUMO, DATA_CRIACAO, ID_SIMPOSIO, ID_AUTOR) VALUES
('Aplicações de IA', 'Estudo sobre aplicações de inteligência artificial.', '2023-09-10', 1, 1),
('Análise de Dados em Tempo Real', 'Exploração de técnicas de análise de dados.', '2023-09-11', 1, 3);

INSERT INTO ARTIGOS_PESSOA (ID_ARTIGO, ID_PESSOA) VALUES
(1, 1),
(1, 2),
(2, 3);

INSERT INTO AVALIACAO_ARTIGO (ID_ARTIGO, ID_COMISSAO_AVALIADORA, NOTA, COMENTARIOS) VALUES
(1, 1, 9, 'Pode melhorar'),
(2, 2, 8, 'Ótimo');