-- com base no enunciado a seguir; elabore o diagrama de entidade e relacionamento,
-- o script de relação de BD, e o script de semeadura de dados

-- um simposio sera organizado na universidade. a organização é de responsabilidade de uma ou mais pessoas
-- serão apresentados nesse simposio varios mini cursos, e cada um deles sera ministrado por apenas uma pessoa. 
-- tambem serão aceitos artigos, sendo que cada um deles possuirá um tema (BD, redes, compiladores, realidade virutual, etc).
-- estes artigos são escritos por no minimo uma pessoa, e não possuem limite de numero de autores. 
-- cada artigo sera encaminhado para uma comissão cientifica, sendo que há uma comissão cientifica para cada tema, 
-- que por sua vez é formada por uma ou mais pessoas, que emitirão um parecer sobre o artigo. 
-- as pessoas se inscreverão no simposio, podendo escolher se querem assistir aos mini cursos(e quais) e/ou palestras(e quais). 

-- primeiro passo(separem os subistantivos como essas entidades se relacionam, definir chaves primarias, foreing key, universidade palestra

CREATE DATABASE SIMPOSIO_TECNOLOGIA;  

USE SIMPOSIO_TECNOLOGIA;

CREATE TABLE PESSOAS(
	ID INT NOT NULL auto_increment primary KEY,
	NOME VARCHAR(255) NOT NULL,
    CPF INT(11) NOT NULL,
    DATA_NASC DATE NOT NULL);

CREATE TABLE MINI_CURSOS(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    DATA_MINICURSO DATE NOT NULL,
    ID_SIMPOSIO INT NOT NULL,
    ID_MINISTRADOR INT NOT NULL,
    CONSTRAINT FK_CURSO_SIMPOSIO foreign key(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID),
    CONSTRAINT FK_CURSO_MINISTRADOR FOREIGN KEY(ID_MINISTRADOR) REFERENCES PESSOAS(ID)
	);
	
CREATE TABLE SIMPOSIO_PESSOA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_SIMPOSIO INT NOT NULL,
    ID_PESSOAS INT NOT NULL,
    CONSTRAINT FK_ID_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY(ID_PESSOAS) REFERENCES PESSOAS(ID)
    );
	
CREATE TABLE SIMPOSIO(
	ID INT NOT NULL auto_increment primary key,
    NOME VARCHAR(200),
    DATA_REALIZACAO DATE
    );
    
    
CREATE TABLE INSCRICAO_MINICURSOS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    ID_MINICURSO INT NOT NULL,
    DATA_INSCRICAO DATE NOT NULL,
    STATUS_INSCRICAO VARCHAR(254) NOT NULL,  
    CONSTRAINT FK_INSCRICAO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID),
    CONSTRAINT FK_INSCRICAO_MINICURSO FOREIGN KEY(ID_MINICURSO) REFERENCES MINI_CURSOS(ID)
);

CREATE TABLE COMISSAO_AVALIADORA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT NOT NULL, 
    CARGO VARCHAR(255),   
    AREA_ESPECIALIZACAO VARCHAR(255) NOT NULL,  
    CONSTRAINT FK_COMISSAO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE ARTIGOS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,  
    RESUMO TEXT,
    DATA_CRIACAO DATE NOT NULL,
    ID_PESSOA INT NOT NULL, 
    CONSTRAINT FK_ARTIGO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE ARTIGOS_PESSOA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ARTIGO INT NOT NULL, 
    ID_PESSOA INT NOT NULL,  
    CONSTRAINT FK_ARTIGO_PUBLICADOR FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGOS(ID),
    CONSTRAINT FK_PESSOA_ARTIGO FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID)
);

CREATE TABLE AVALIACAO_ARTIGO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ARTIGO INT NOT NULL, 
    ID_AVALIADOR INT NOT NULL, 
    NOTA INT NOT NULL,  
    COMENTARIOS TEXT, 
    CONSTRAINT FK_AVALIACAO_ARTIGO FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGOS(ID),
    CONSTRAINT FK_AVALIADOR_PESSOA FOREIGN KEY(ID_AVALIADOR) REFERENCES PESSOAS(ID)
);

CREATE TABLE PALESTRAS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    DATA_PALESTRA DATE NOT NULL,
    ID_SIMPOSIO INT NOT NULL,
    ID_MINISTRADOR INT NOT NULL,
    CONSTRAINT FK_PALESTRA_SIMPOSIO FOREIGN KEY(ID_SIMPOSIO) REFERENCES SIMPOSIO(ID),
    CONSTRAINT FK_PALESTRA_MINISTRADOR FOREIGN KEY(ID_MINISTRADOR) REFERENCES PESSOAS(ID)
);

CREATE TABLE INSCRICAO_PALESTRA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    ID_PALESTRA INT NOT NULL,
    DATA_INSCRICAO DATE NOT NULL,
    STATUS_INSCRICAO VARCHAR(254) NOT NULL,  
    CONSTRAINT FK_INSCRICAO_PESSOA_PALESTRA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID),
    CONSTRAINT FK_INSCRICAO_PALESTRA FOREIGN KEY(ID_PALESTRA) REFERENCES PALESTRAS(ID)
);